SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE DATABASE ent;
USE ent;
DROP TABLE Utilisateur;
DROP TABLE Cours;

CREATE TABLE IF NOT EXISTS Cours (
  idCours INT NOT NULL AUTO_INCREMENT,
  intule VARCHAR(45) NOT NULL,
  code VARCHAR(45) NOT NULL,
  description VARCHAR(45) NULL,
  Utilisateur_idUtilisateur INT NOT NULL,
  PRIMARY KEY (idCours),
    CONSTRAINT fk_Cours_Utilisateur1
    FOREIGN KEY (Utilisateur_idUtilisateur)
    REFERENCES Utilisateur (idUtilisateur)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Utilisateur (
  idUtilisateur INT NOT NULL AUTO_INCREMENT,
  nom VARCHAR(45) NOT NULL,
  prenom VARCHAR(45) NOT NULL,
  motDePasse TEXT BINARY NOT NULL,
  mail VARCHAR(45) UNIQUE NOT NULL,
  role VARCHAR(45) NOT NULL,
  codeActiv VARCHAR(45) NULL,
  Cours_idCours INT NULL,
  PRIMARY KEY (idUtilisateur),
  CONSTRAINT fk_Utilisateur_Cours
    FOREIGN KEY (Cours_idCours)
    REFERENCES Cours (idCours)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO Cours 
VALUES (NULL , 'math', 'F', 'tgztgg', 1);